-- DROP
DROP TABLE CUSTOMER;
DROP SEQUENCE CUSTOMER_ID_SQ;
-- CREATE TABLE & SEQUENCE
CREATE TABLE CUSTOMER(
    ID NUMBER(9) PRIMARY KEY,
    PHONE VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    POINT NUMBER(9) DEFAULT 1000);
CREATE SEQUENCE CUSTOMER_ID_SQ
    MAXVALUE 999999999 NOCACHE NOCYCLE;
-- 가입
INSERT INTO CUSTOMER VALUES (CUSTOMER_ID_SQ.NEXTVAL, '010-9999-9999','홍길동',1000);
-- 폰조회
SELECT * FROM CUSTOMER WHERE PHONE LIKE '%9999';
SELECT * FROM CUSTOMER WHERE PHONE LIKE '%'||'9999';
-- 전체조회
SELECT * FROM CUSTOMER;
COMMIT;
