-- [VIII] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ 
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM  NUMBER(4)    PRIMARY KEY, -- 시퀀스 이용
    NAME VARCHAR2(30) NOT NULL,
    TEL  VARCHAR2(30) UNIQUE, -- NULL허용, 유일한 값
    ADDRESS VARCHAR2(300),
    LAST_MODIFYED DATE DEFAULT SYSDATE
);
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동',NULL, '서울시 용산구'); -- 3번 실행
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999', '서울시 강남구 강남대로94길 13 삼겸빌딩 402');
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SEQ.NEXTVAL, '박길동', '010-9999-9999', '서울시 강남구 강남대로94길 13 삼겸빌딩 402');
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-8888','서울시 영등포구');
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재 시퀀스 값
COMMIT;

-- ex. 초기값 101부터 최대값 999,999까지 1씩 증가하는 test_seq 시퀀스를 생성
CREATE SEQUENCE TEST_SEQ START WITH 101 MAXVALUE 999999 NOCACHE NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; -- 시퀀스의 현재 값이 없어서 에러
SELECT TEST_SEQ.NEXTVAL FROM DUAL;

--  
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO   NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL);
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ MAXVALUE 9999999999 NOCACHE NOCYCLE;
CREATE TABLE MEMBER(
    mNO     NUMBER(10) PRIMARY KEY,
    mNAME   VARCHAR2(30) NOT NULL,
    mPW     VARCHAR2(30) CHECK(LENGTH(mPW)<=8),
    mEMAIL  VARCHAR2(30) UNIQUE,
    mPOINT  NUMBER(10)   CHECK(mPOINT>=0),
    mRDATE  DATE         DEFAULT SYSDATE,
    LEVELNO NUMBER(1)   REFERENCES MEMBER_LEVEL(LEVELNO) );

INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, 0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, 1);
SELECT * FROM MEMBER;
-- 테스트 출력 내용
SELECT MNO, MNAME, TO_CHAR(MRDATE,'YYYY-MM-DD') MRDATE, MEMAIL mmail, 
        mPOINT POINT, LEVELNAME||'고객' levelname
    FROM MEMBER_LEVEL L, MEMBER M
    WHERE L.LEVELNO = M.LEVELNO;
SELECT MNO, MNAME, TO_CHAR(MRDATE,'YYYY-MM-DD') MRDATE, MEMAIL mmail, 
        mPOINT POINT, CONCAT(LEVELNAME,'고객') levelname
    FROM MEMBER_LEVEL L, MEMBER M
    WHERE L.LEVELNO = M.LEVELNO;
